server:
  port: 8085
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**
        - id: invitation-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/invitations/**
        - id: organization-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/organizations/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
