server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/organizationdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: organization-service

management:
  endpoints:
    web:
      base-path: /actuator
      path-mapping:
        health: healtz
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    defaults:
      enabled: true
