server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/organizationdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: organization-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /

management:
  endpoints:
    web:
      base-path: /actuator
      path-mapping:
        health: healtz
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    defaults:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.amqp: INFO
    com.pm.organizationservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN
    org.hibernate.resource.transaction: WARN
    org.hibernate.internal.AbstractSharedSessionContract: WARN
