spring:
  datasource:
    url: jdbc:mysql://localhost:3307/invitationdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

management:
  endpoints:
    web:
      base-path: /actuator
      path-mapping:
        health: healtz
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    defaults:
      enabled: true
